CREATE TABLE `imcba_survey01` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `past1` int(3) DEFAULT NULL,
  `past2` int(3) DEFAULT NULL,
  `past3` int(3) DEFAULT NULL,
  `past4` int(3) DEFAULT NULL,
  `pres1` int(3) DEFAULT NULL,
  `pres2` int(3) DEFAULT NULL,
  `pres3` int(3) DEFAULT NULL,
  `pres4` int(3) DEFAULT NULL,
  `future1` int(3) DEFAULT NULL,
  `future2` int(3) DEFAULT NULL,
  `future3` int(3) DEFAULT NULL,
  `future4` int(3) DEFAULT NULL,
  `rec1` varchar(160) DEFAULT NULL,
  `rec2` varchar(160) DEFAULT NULL,
  `rec3` varchar(160) DEFAULT NULL,
  `rec4` varchar(160) DEFAULT NULL,
  `age` int(3) DEFAULT NULL,
  `sex` varchar(6) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  `fname` varchar(30) DEFAULT NULL,
  `mname` varchar(30) DEFAULT NULL,
  `lname` varchar(45) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `php_id` varchar(64) DEFAULT NULL,
  `time` timestamp DEFAULT LOCALTIME,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;
